version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=014650260613.dkr.ecr.ap-south-1.amazonaws.com/openid-employee-service
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Module ...
      - ./gradlew build candidate build dockerPush helmDeploy -i --stacktrace -Pdocker_registry=$REPOSITORY_URI -Dorg.ajoberstar.grgit.auth.username=$GITHUB_USER -Dorg.ajoberstar.grgit.auth.password=$GITHUB_PASSWORD -I init.gradle
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying the Helm Chart...
#artifacts:
  #files: imagedefinitions.json